### ISSUE TITLE
Setup issue with server

### ISSUE THREAD

**Issue by mmguide2003** [codingfriend1/meanbase-1.0.0#1]
I'm using mac and when I grunt serve I get the following error:

Express server listening on 9000, in development mode
.../meanbase-1.0.0/server/init/themes.js:11
	  if(!activeTheme[0] || !activeTheme[0].url) { activeTheme[0].url = ''; }
	                                                                  ^
TypeError: Cannot set property 'url' of undefined

at Promise.<anonymous> (.../meanbase-1.0.0/server/init/themes.js:11:68)
    at Promise.<anonymous> (...../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (.../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (.../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (..../meanbase-1.0.0/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (..../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (..../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (....../meanbase-1.0.0/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)

**Comment by codingfriend1** [comment]
Sorry for taking so long to reply, how many valid themes do you have in your themes folder?

Some code pushes I've done lately may have fixed this issue. Will you try again and tell me if the problem persists?

**Comment by mmguide2003** [comment]
Hi, Thanks for the response. I've pulled the updates but now I have this error on running grunt:
    
    Running "wiredep:target" (wiredep) task
    Warning: Cannot read property 'main' of undefined Use --force to continue.
    Aborted due to warnings.
    Execution Time (2015-05-31 09:09:33 UTC)
    loading tasks      256ms  ▇ 2%
    clean:server       276ms  ▇ 2%
    concurrent:server   9.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇      75%
    wiredep:target      2.4s  ▇▇▇▇▇▇▇▇ 18%
    Total 13.1s

**Comment by codingfriend1** [comment]
So as I have been building the app I've let the actual grunt build fall behind. I've done a lot of work on it this weekend and hopefully will have a working product in a couple days. For now you can try to pull from dev, since that will have the most recent changes. Also, try using the --force option to ignore jshint errors until we get those fixed.

I appreciate you looking into it and helping me find these bugs!

**Comment by mmguide2003** [comment]
I've managed to get it up and running but have a blank page

    Express server listening on 9000, in development mode
    activeTheme []
    could not find any themes

Pretty new at MEAN & git, so maybe my lack of knowledge.

**Comment by mmguide2003** [comment]
Seems to be working now downloaded latest master
